import sqlite3
import os
from datetime import date

db_path = "to-do_list.db"


def main():
    if not os.path.exists(db_path):
        conn = None
        try:
            # create connection to db_file
            conn = sqlite3.connect(db_path)

            # create cursor object
            cur = conn.cursor()

            # sql statement to create To-do_list table
            sql = """CREATE TABLE Book To-do_list (To-do_ID INTEGER PRIMARY KEY NOT NULL, 
                                                   Description TEXT NOT NULL,
                                                   DueDate TEXT NOT NULL,
                                                   Priority TEXT NOT NULL,
                                                   PriorityNumber INTEGER NOT NULL,
                                                   Status TEXT NOT NULL,
                                                   StatusNumber INTEGER NOT NULL)"""

            # create To-do_list table
            cur.execute(sql)

            # commit changes
            conn.commit()
        except sqlite3.Error as err:
            # print error message generated by sql
            print(err)
        finally:
            # close connection if there was any
            if conn is not None:
                conn.close()
    else:
        # if the database file already exists, then update all the status and status number column
        update_status()
        menu()


""" The main function 
creates to-do_list.db, which is the database for the program if none
exists. After creating the database, it creates the the table that will
be used in this program. The table's name is To-do_list. If the database
already exists, then the main function will go ahead and update the 
status for all the rows in the table by calling the update_status 
function and then call the menu function."""
